### ISSUE TITLE
`Println` can be used in several places

### ISSUE THREAD

**Issue by jlapeyre** [PtFEM/NumericalMethodsforEngineers.jl#2]
In lines like the following

https://github.com/PtFEM/NumericalMethodsforEngineers.jl/blob/2f011794612f6e0bd7fd051302b5678dbec0b476/examples/ch04/ex.5.1B_symata.jl#L14

you may want to use `Println`.

**Comment by goedman** [comment]
Thank you, much better than my code and not just because of the Println()! In fact, I have never done a 2nd pass through NumericalMethodsforEngineers.jl, always postponed that until Julia 1.0 was available. But now is a good time to do that and at the same time have a closer look at how I have used Symata.

**Comment by jlapeyre** [comment]
Good. Some of this is not very discoverable. I'm not sure how you'd know that `Println` exists... hmm, maybe TAB completion.
